#if !defined(RYSV_CHECK_REGULATION_HPP_INCLUDE_GUARD)
#define RYSV_CHECK_REGULATION_HPP_INCLUDE_GUARD


#define RYSV_CHECK_REGULATION(...)

#endif // !defined(RYSV_CHECK_REGULATION_HPP_INCLUDE_GUARD)
